### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arqmail** [JoelGMSec/EvilnoVNC#35]
broken codes or bugs i believe, i tried making it work, but wont save cookies or keylogs in downloads folder, file permission in downloads folder is also read only

**Comment by arqmail** [comment]
Does not work on Kali Linux

**Comment by purpleracc00n** [comment]
This appears to be caused by some python dependency issue (surprise surprise) in the cookies.py script.

`
Traceback (most recent call last):
  File "/home/user/cookies.py", line 10, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
`

To fix this, you will have to install pycryptodome library within the docker container

`sudo docker exec -it <container_id> bash
 sudo pip3 install pycryptodome --break-system-packages
`

At least this worked for me. Just a workaround until this gets updated maybe.

Think I've also seen a similar error with keylogger.py too.

**Comment by 0xyrrah** [comment]
check this tool on this telegram https://t.me/+5DHzUrWKU00zYjM0

**Comment by JoelGMSec** [comment]
Tested and working like a charm :)
