### ISSUE TITLE
URL not accessible

### ISSUE THREAD

**Issue by cliketheletter** [JoelGMSec/EvilnoVNC#37]
Hello, when trying to run this script the url provided is just http://localhost

Upon proceeding it shows unable to connect to site "An error occurred during a connection to localhost. " how to resolve this?

Please see image below, thanks.
![Screenshot 2024-07-21 173901](https://github.com/user-attachments/assets/78215de1-1f6c-4416-ae6b-9c22f70348f9)

**Comment by JoelGMSec** [comment]
Recently some chromium updates don't allow to run with the root user.
I did a small rollback to Debian instead of Alpine, which seems to be more stable and allows easier debugging.
With this rollback, the ability to send the User-Agent and the original language is lost, but I'll try to add that function ASAP.

So far I've tested it on several systems and it works perfectly :)

**Comment by JoelGMSec** [comment]
User-Agent and Language working again, improved stability too!

**Comment by NotWeelee** [comment]
I'm running into the same issue where the tool output only gives me "[+] URL: http://localhost" and receiving a 'Unable to connect. An error occurred during a connection to localhost." from my browser when I attempt to navigate to "http://localhost". I have also run "ss -tulpn" to see what ports on the host is in use and can't identify one that belongs to docker or EvilnoVNC.

Where can I start to troubleshoot this?
